version: "3"
services:
  httpd:
    image: httpd:2.4
    ports:
      - 8080:80
      - 8443:443
    depends_on:
      - db
    volumes:
      - ./web:/var/www/html
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: bdairam
      MYSQL_DATABASE: shop
      MYSQL_USER: shopkeeper
      MYSQL_PASSWORD: repeekpohs
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
