version: "3"
services:
  web:
    build: ./web
    hostname: apacheC7
    ports:
      - 8000:80
      - 8443:443
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: bdairam
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - 8888:8888
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
