version: "3"
services:
  httpd:
    image: httpd:2.4
    container_name: palol-httpd
    ports:
      - 8080:80
      - 8443:443
    depends_on:
      - db
      - php-fpm
    volumes:
      - ./web:/var/www/html
      - ./var/log/httpd:/var/log/httpd
  php-fpm:
      build: ./var/phpdocker
      container_name: palol-php-fpm
      volumes:
        - ./web:/var/www/html
        - ./var/conf/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
  db:
    image: mariadb
    container_name: palol-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: bdairam
      MYSQL_DATABASE: shop
      MYSQL_USER: shopkeeper
      MYSQL_PASSWORD: repeekpohs
    volumes:
      - ./var/log/mariadb:/var/log/mariadb
  adminer:
    image: adminer
    container_name: palol-adminer
    restart: always
    ports:
      - 8081:8080
